import { Course } from "./schema";

export const courses: Course[] = [
    {
        id: 1,
        title: "Nepali",
        imageSrc: "/assets/nepal_flag.svg",
        units: [
            {
                id: 1,
                title: "Unit 1",
                description: "Learn the basics of Nepali",
                order: 1,
                lessons: [
                    {
                        id: 1,
                        unitId: 1,
                        title: "Basics",
                        order: 1,
                        completed: false,
                        challenges: [
                            {
                                id: 1,
                                lessonId: 1,
                                type: "SELECT",
                                question: 'Which one of these is "the man"?',
                                order: 1,
                                challengeOptions: [
                                    {
                                        id: 1,
                                        challengeId: 1,
                                        text: "मान्छे (Manche)",
                                        correct: true,
                                        imageSrc: "/assets/man.svg",
                                        audioSrc: null,
                                    },
                                    {
                                        id: 2,
                                        challengeId: 1,
                                        text: "घर (Ghar)",
                                        correct: false,
                                        imageSrc: "/assets/house.svg",
                                        audioSrc: null,
                                    },
                                    {
                                        id: 3,
                                        challengeId: 1,
                                        text: "स्याउ (Syau)",
                                        correct: false,
                                        imageSrc: "/assets/apple.svg",
                                        audioSrc: null,
                                    },
                                ],
                            },

                            {
                                id: 3,
                                lessonId: 1,
                                type: "SELECT",
                                question: 'Which one of these is "the apple"?',
                                order: 3,
                                challengeOptions: [
                                    {
                                        id: 7,
                                        challengeId: 3,
                                        text: "स्याउ (Syau)",
                                        correct: true,
                                        imageSrc: "/assets/apple.svg",
                                        audioSrc: null,
                                    },
                                    {
                                        id: 8,
                                        challengeId: 3,
                                        text: "मान्छे (Manche)",
                                        correct: false,
                                        imageSrc: "/assets/man.svg",
                                        audioSrc: null,
                                    },
                                    {
                                        id: 9,
                                        challengeId: 3,
                                        text: "घर (Ghar)",
                                        correct: false,
                                        imageSrc: "/assets/house.svg",
                                        audioSrc: null,
                                    },
                                ],
                            },

                            {
                                id: 5,
                                lessonId: 1,
                                type: "SELECT",
                                question: 'Which one of these is "the house"?',
                                order: 5,
                                challengeOptions: [
                                    {
                                        id: 13,
                                        challengeId: 5,
                                        text: "घर (Ghar)",
                                        correct: true,
                                        imageSrc: "/assets/house.svg",
                                        audioSrc: null,
                                    },
                                    {
                                        id: 14,
                                        challengeId: 5,
                                        text: "स्याउ (Syau)",
                                        correct: false,
                                        imageSrc: "/assets/apple.svg",
                                        audioSrc: null,
                                    },
                                    {
                                        id: 15,
                                        challengeId: 5,
                                        text: "मान्छे (Manche)",
                                        correct: false,
                                        imageSrc: "/assets/man.svg",
                                        audioSrc: null,
                                    },
                                ],
                            },

                        ],
                    },
                    {
                        id: 2,
                        unitId: 1,
                        title: "Greetings",
                        order: 2,
                        completed: false,
                        challenges: [
                            {
                                id: 19,
                                lessonId: 2,
                                type: "ASSIST",
                                question: '"Hello"',
                                order: 1,
                                challengeOptions: [
                                    {
                                        id: 25,
                                        challengeId: 19,
                                        text: "नमस्ते (Namaste)",
                                        correct: true,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                    {
                                        id: 26,
                                        challengeId: 19,
                                        text: "धन्यवाद (Dhanyabad)",
                                        correct: false,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                    {
                                        id: 27,
                                        challengeId: 19,
                                        text: "शुभ रात्री (Subha Ratri)",
                                        correct: false,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                ],
                            },
                            {
                                id: 20,
                                lessonId: 2,
                                type: "SELECT",
                                question: 'Which one of these is "Namaste"?',
                                order: 2,
                                challengeOptions: [
                                    {
                                        id: 28,
                                        challengeId: 20,
                                        text: "नमस्ते (Namaste)",
                                        correct: true,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                    {
                                        id: 29,
                                        challengeId: 20,
                                        text: "घर (Ghar)",
                                        correct: false,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                    {
                                        id: 30,
                                        challengeId: 20,
                                        text: "स्याउ (Syau)",
                                        correct: false,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                ],
                            },
                            {
                                id: 4,
                                lessonId: 2,
                                type: "ASSIST",
                                question: '"What does Thank You mean in nepali ?"',
                                order: 3,
                                challengeOptions: [
                                    {
                                        id: 10,
                                        challengeId: 4,
                                        text: "धन्यवाद (Dhanyabad)",
                                        correct: true,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                    {
                                        id: 11,
                                        challengeId: 4,
                                        text: "नमस्ते (Namaste)",
                                        correct: false,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                    {
                                        id: 12,
                                        challengeId: 4,
                                        text: "शुभ रात्री (Subha Ratri)",
                                        correct: false,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                ],
                            },
                            {
                                id: 6,
                                lessonId: 2,
                                type: "ASSIST",
                                question: '"What does Good Night mean in nepali ?"',
                                order: 4,
                                challengeOptions: [
                                    {
                                        id: 16,
                                        challengeId: 6,
                                        text: "शुभ रात्री (Subha Ratri)",
                                        correct: true,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                    {
                                        id: 17,
                                        challengeId: 6,
                                        text: "धन्यवाद (Dhanyabad)",
                                        correct: false,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                    {
                                        id: 18,
                                        challengeId: 6,
                                        text: "नमस्ते (Namaste)",
                                        correct: false,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                ],
                            },
                        ],
                    },
                    {
                        id: 3,
                        unitId: 1,
                        title: "Intro",
                        order: 3,
                        completed: false,
                        challenges: [
                            {
                                id: 21,
                                lessonId: 3,
                                type: "ASSIST",
                                question: '"I am Nepali"',
                                order: 1,
                                challengeOptions: [
                                    {
                                        id: 31,
                                        challengeId: 21,
                                        text: "म नेपाली हुँ (Ma Nepali hu)",
                                        correct: true,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                    {
                                        id: 32,
                                        challengeId: 21,
                                        text: "मेरो नाम राम हो (Mero naam Ram ho)",
                                        correct: false,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                    {
                                        id: 33,
                                        challengeId: 21,
                                        text: "नमस्ते (Namaste)",
                                        correct: false,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                ],
                            },
                        ],
                    },
                ],
            },
            {
                id: 2,
                title: "Unit 2",
                description: "Moderate - Numbers & Phrases",
                order: 2,
                lessons: [
                    {
                        id: 4,
                        unitId: 2,
                        title: "Numbers",
                        order: 1,
                        completed: false,
                        challenges: [
                            {
                                id: 7,
                                lessonId: 4,
                                type: "SELECT",
                                question: 'Which one of these is "One"?',
                                order: 1,
                                challengeOptions: [
                                    {
                                        id: 19,
                                        challengeId: 7,
                                        text: "एक (Ek)",
                                        correct: true,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                    {
                                        id: 20,
                                        challengeId: 7,
                                        text: "दुई (Dui)",
                                        correct: false,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                    {
                                        id: 21,
                                        challengeId: 7,
                                        text: "तीन (Tin)",
                                        correct: false,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                ],
                            },
                        ],
                    },
                ],
            },
            {
                id: 3,
                title: "Unit 3",
                description: "Hard - Sentences & Grammar",
                order: 3,
                lessons: [
                    {
                        id: 5,
                        unitId: 3,
                        title: "Sentences",
                        order: 1,
                        completed: false,
                        challenges: [
                            {
                                id: 8,
                                lessonId: 5,
                                type: "ASSIST",
                                question: '"My name is Ram"',
                                order: 1,
                                challengeOptions: [
                                    {
                                        id: 22,
                                        challengeId: 8,
                                        text: "मेरो नाम राम हो (Mero naam Ram ho)",
                                        correct: true,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                    {
                                        id: 23,
                                        challengeId: 8,
                                        text: "म नेपाली हुँ (Ma Nepali hu)",
                                        correct: false,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                    {
                                        id: 24,
                                        challengeId: 8,
                                        text: "तपाईंलाई कस्तो छ? (Tapailai kasto cha?)",
                                        correct: false,
                                        imageSrc: null,
                                        audioSrc: null,
                                    },
                                ],
                            },
                        ],
                    },
                ],
            },
        ],
    },
];
